version: "3"

services:
  db:
    image: mysql:5.7
    ports:
      - 3315:3306
    volumes:
     - ./containers/db57:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "cms"

  xmr:
    image: xibosignage/xibo-xmr:latest
    ports:
     - "9505:9505"
    environment:
      XMR_DEBUG: "true"
      IPV6RESPSUPPORT: "false"
      IPV6PUBSUPPORT: "false"

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
     - ./:/var/www/cms
    ports:
     - "80:80"
    environment:
      CMS_DEV_MODE: "true"
      MYSQL_DATABASE: "cms"

  quickchart:
    image: ianw/quickchart