version: "3"

services:
  db:
    image: mysql:5.7
    ports:
    - 3315:3306
    volumes:
    - ./containers/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "cms"

  xmr:
    image: xibosignage/xibo-xmr:latest
    ports:
    - "9505:9505"
    environment:
      XMR_DEBUG: "true"
      IPV6RESPSUPPORT: "false"
      IPV6PUBSUPPORT: "false"

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
    - ./:/var/www/cms
    ports:
    - "80:80"
    environment:
      CMS_DEV_MODE: "true"
      MYSQL_DATABASE: "cms"

  swagger:
    image: swaggerapi/swagger-ui:latest
    ports:
    - "8080:8080"
    environment:
    - API_URL=http://localhost/swagger.json

  quickchart:
    image: ianw/quickchart

networks:
  default:
    external:
      name: mongodb_mongodb