version: "3"

services:
  db:
    image: mysql:8.0
    ports:
    - "3315:3306"
    volumes:
    - ./containers/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "cms"

  xmr:
    image: ghcr.io/xibosignage/xibo-xmr:latest
    ports:
    - "9505:9505"
    environment:
      XMR_DEBUG: "true"
      IPV6RESPSUPPORT: "false"
      IPV6PUBSUPPORT: "false"

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
    - ./:/var/www/cms
    ports:
    - "80:80"
    environment:
      CMS_DEV_MODE: "true"
      MYSQL_DATABASE: "cms"

  memcached:
    image: memcached:alpine
    command: memcached -m 15

  swagger:
    image: swaggerapi/swagger-ui:latest
    ports:
    - "8080:8080"
    environment:
    - API_URL=http://localhost/swagger.json

  quickchart:
    image: ianw/quickchart
